### ISSUE TITLE
Manage cookies for android?

### ISSUE THREAD

**Issue by mesopelagique** [mesopelagique/form-detail-WebArea#3]
when connecting to database using web request, rest request we receive an `4DSIS_<baseName>` cookie with session id inside (if database is configured to use scalable session)
http headers is `Set-Cookie`

for iOS it stored automatically in `HTTPCookieStorage.shared` (because I say it my network layer code, to use it)
But my iOS `webview` do not use that, it have  its own cookie storage
So I add some code to inject cookies from storage to another

On android @quentinmarciset how it works?

**Comment by quentinmarciset** [comment]
Handled in 2 ways :
- collected from a response and inserted with an [Interceptor](https://square.github.io/okhttp/features/interceptors/)
- using [CookieManager](https://developer.android.com/reference/android/webkit/CookieManager)
